/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLogin: typeof import('./src/components/AuthLogin.vue')['default']
    AuthLogout: typeof import('./src/components/AuthLogout.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    UserProfileActivities: typeof import('./src/components/userProfile/UserProfileActivities.vue')['default']
    UserProfileAddress: typeof import('./src/components/userProfile/UserProfileAddress.vue')['default']
    UserProfileInfo: typeof import('./src/components/userProfile/UserProfileInfo.vue')['default']
    UserProfileStudentCourses: typeof import('./src/components/userProfile/UserProfileStudentCourses.vue')['default']
    UserProfileTeacherCourses: typeof import('./src/components/userProfile/UserProfileTeacherCourses.vue')['default']
    UserViewModal: typeof import('./src/components/userProfile/modals/UserViewModal.vue')['default']
  }
}
